### PR TITLE
feat(utils test): add vue utils test

### PR DESCRIPTION
**Pull request by FliPPeDround**
I think it's a cool project, but currently the project doesn't have unit tests, which makes it impossible for users to check that their code is correct. So, the pr introduces the vue units test environment and writes "lifecycle" unit tests.

### CODE REVIEW

**Comment by webfansplz** [comment]
Thanks for your contribution, but the developers always take the challenges online (not cloned the probject and run tests). I know the questions missing the code judge now, but the best way that i think we should on the SFC Playground (runtime) to handle it.

**Comment by FliPPeDround** [comment]
yes, I always think that chanllenges online is the most convenient way，but it's not means that we can't support other ways (cloned the probject and run tests)  like type-challenges, if developers watch all the test become pass from failed，will get great sense of achievement. this is my suggest: offer more one way to join vuejs-challenges !

**Comment by FliPPeDround** [comment]
and, we can use [stackblitz](https://stackblitz.com/edit/vitest-dev-vitest-dkandk?file=test/App.vue) to suppose online test, this is amazing

**Comment by FliPPeDround** [comment]
maybe you can [try it](https://stackblitz.com/edit/node-hhf6tt?file=questions%2F1-hello-word%2FApp.vue)

**Comment by webfansplz** [comment]
> and, we can use [stackblitz](https://stackblitz.com/edit/vitest-dev-vitest-dkandk?file=test/App.vue) to suppose online test, this is amazing

It's really amazing !

**Pull request closed without merging**
